
name: klx-training-pre-pr-check

on:
  workflow_dispatch:
    inputs:
      case1x1:
        description: 'e.g. model:framework:hardwareID:1:1:1 (empty means not to execute)'
      case1x8:
        description: 'e.g. model:framework:hardwareID:1:8:1 (empty means not to execute)'
      dataset_path:
        description: 'dataset path filled into test_conf.py'
        required: true
jobs:
  run-klx-training-test:
    runs-on: [ self-hosted, klx, r480 ]
    steps:
